<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageVersion Include="Meziantou.Polyfill" Version="1.0.101" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.2" />
  </ItemGroup>
</Project>